services:
  - type: web
    name: LeagueOn
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: league-simple-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: LEAGUE_ADMIN_USERNAME
        sync: false
        value: Admin
      - key: LEAGUE_ADMIN_PASSWORD
        sync: false
        value: admin123
      - key: FLASK_ENV
        value: production

databases:
  - name: league-simple-db
    plan: free
